'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {createClient} from '@supabase/supabase-js';
import type {Document,Client,Property} from '../lib/data';
const db=process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY?createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY):null;
type Item={id:string;organization_id:string;document_id:string;description:string;item_name?:string|null;quantity:number;unit:string;unit_price:number;tax_rate:number;discount_type?:string;discount_value?:number};
type Catalog={id:string;organization_id:string;name:string;description:string|null;unit:string;unit_price:number;tax_rate:number};
type Payment={id:string;organization_id:string;document_id:string;amount:number;method:string;payment_date:string;reference:string|null;notes:string|null};
const money=(n:number)=>Number(n||0).toLocaleString('en-US',{style:'currency',currency:'USD'});
const today=()=>new Date().toLocaleDateString('en-CA');
const itemTotals=(i:Item)=>{const base=Number(i.quantity)*Number(i.unit_price);const discount=Math.min(base,i.discount_type==='percent'?base*Number(i.discount_value||0)/100:Number(i.discount_value||0));const taxable=base-discount;return {base,discount,tax:taxable*Number(i.tax_rate)/100,total:taxable*(1+Number(i.tax_rate)/100)};};
export default function BillingStudio({organizationId,documents,clients,properties}:{organizationId:string;documents:Document[];clients:Client[];properties:Property[]}){
 const [doc,setDoc]=useState('');const [items,setItems]=useState<Item[]>([]);const [payments,setPayments]=useState<Payment[]>([]);const [catalog,setCatalog]=useState<Catalog[]>([]);
 const [sections,setSections]=useState<string[]>(['details','items']);const [itemOpen,setItemOpen]=useState(false);const [editing,setEditing]=useState<string|null>(null);
 const [name,setName]=useState('');const [description,setDescription]=useState('');const [quantity,setQuantity]=useState('1');const [unit,setUnit]=useState('each');const [price,setPrice]=useState('');const [tax,setTax]=useState('0');const [discount,setDiscount]=useState('0');const [discountType,setDiscountType]=useState('amount');const [saveCatalog,setSaveCatalog]=useState(false);
 const [amount,setAmount]=useState('');const [method,setMethod]=useState('check');const [when,setWhen]=useState(today());const [reference,setReference]=useState('');const [terms,setTerms]=useState('');const [issued,setIssued]=useState(today());const [due,setDue]=useState('');const [po,setPo]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 const key=`jtg-billing-v06-${organizationId}`;const catalogKey=`jtg-catalog-v08-${organizationId}`;
 const current=documents.find(d=>d.id===doc);const customer=clients.find(c=>c.id===current?.client_id);const property=properties.find(p=>p.id===current?.property_id);
 const load=useCallback(async()=>{if(!db){const saved=JSON.parse(localStorage.getItem(key)||'{}');setItems(saved.items||[]);setPayments(saved.payments||[]);setCatalog(JSON.parse(localStorage.getItem(catalogKey)||'[]'));return;}const [a,b,c]=await Promise.all([db.from('document_items').select('*').eq('organization_id',organizationId),db.from('document_payments').select('*').eq('organization_id',organizationId),db.from('billing_catalog').select('*').eq('organization_id',organizationId).order('name')]);if(a.error||b.error||c.error){setError((a.error||b.error||c.error)?.message||'Unable to load billing data. Run upgrade-v0.8.sql.');return;}setItems(a.data||[]);setPayments(b.data||[]);setCatalog(c.data||[])},[organizationId,key,catalogKey]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{setTerms(current?.contract_terms||'');setIssued(current?.issue_date||today());setDue((current as Document&{due_date?:string|null})?.due_date||'');setPo((current as Document&{purchase_order?:string|null})?.purchase_order||'')},[current?.id,current?.contract_terms,current?.issue_date]);
 const currentItems=items.filter(i=>i.document_id===doc);const currentPayments=payments.filter(p=>p.document_id===doc);
 const sums=useMemo(()=>currentItems.reduce((a,i)=>{const v=itemTotals(i);return {subtotal:a.subtotal+v.base,discount:a.discount+v.discount,tax:a.tax+v.tax,total:a.total+v.total}},{subtotal:0,discount:0,tax:0,total:0}),[currentItems]);
 const total=currentItems.length?sums.total:Number(current?.amount||0);const received=currentPayments.reduce((s,p)=>s+Number(p.amount),0);const remaining=total-received;
 const toggle=(s:string)=>setSections(p=>p.includes(s)?p.filter(x=>x!==s):[...p,s]);
 const localSave=(table:'items'|'payments',next:Item[]|Payment[])=>{const result={items:table==='items'?next:items,payments:table==='payments'?next:payments};localStorage.setItem(key,JSON.stringify(result));setItems(result.items as Item[]);setPayments(result.payments as Payment[])};
 function openItem(i?:Item){setEditing(i?.id||null);setName(i?.item_name||i?.description||'');setDescription(i?.item_name?i.description:'');setQuantity(String(i?.quantity||1));setUnit(i?.unit||'each');setPrice(i?String(i.unit_price):'');setTax(i?String(i.tax_rate):'0');setDiscount(i?String(i.discount_value||0):'0');setDiscountType(i?.discount_type||'amount');setSaveCatalog(false);setItemOpen(true);setError('')}
 function pickCatalog(id:string){const c=catalog.find(c=>c.id===id);if(c){setName(c.name);setDescription(c.description||'');setPrice(String(c.unit_price));setUnit(c.unit);setTax(String(c.tax_rate))}}
 async function submitItem(e:React.FormEvent){e.preventDefault();setError('');const q=Number(quantity),p=Number(price),t=Number(tax),d=Number(discount);if(!current||!name.trim()||![q,p,t,d].every(Number.isFinite)||q<=0||p<0||t<0||t>100||d<0||(discountType==='percent'&&d>100)||(discountType==='amount'&&d>q*p))return setError('Please check the item name, quantity, price, tax and discount.');setBusy(true);const row={organization_id:organizationId,document_id:doc,item_name:name.trim(),description:description.trim(),quantity:q,unit:unit.trim()||'each',unit_price:p,tax_rate:t,discount_type:discountType,discount_value:d};try{if(db){const query=editing?db.from('document_items').update(row).eq('id',editing).eq('organization_id',organizationId):db.from('document_items').insert(row);const {error:e}=await query;if(e)throw e;if(saveCatalog){const {error:ce}=await db.from('billing_catalog').insert({organization_id:organizationId,name:name.trim(),description:description.trim(),unit:row.unit,unit_price:p,tax_rate:t});if(ce)throw ce}await load()}else{const next=editing?items.map(i=>i.id===editing?{...i,...row}:i):[...items,{...row,id:crypto.randomUUID()}];localSave('items',next);if(saveCatalog){const nextCat=[...catalog,{id:crypto.randomUUID(),organization_id:organizationId,name:name.trim(),description:description.trim(),unit:row.unit,unit_price:p,tax_rate:t}];setCatalog(nextCat);localStorage.setItem(catalogKey,JSON.stringify(nextCat))}}setItemOpen(false);setMessage('Line item saved.')}catch(e){setError(e instanceof Error?e.message:'Unable to save item')}finally{setBusy(false)}}
 async function saveDetails(){if(!current)return;setError('');setBusy(true);const row={contract_terms:terms,issue_date:issued,due_date:due||null,purchase_order:po||null};try{if(db){const {error:e}=await db.from('documents').update(row).eq('id',current.id).eq('organization_id',organizationId);if(e)throw e}else{const k='jtg-hq-demo-v1';const value=JSON.parse(localStorage.getItem(k)||'{}');value.documents=(value.documents||[]).map((d:Document)=>d.id===current.id?{...d,...row}:d);localStorage.setItem(k,JSON.stringify(value))}setMessage('Document details saved. Reload if you need to refresh the document list.')}catch(e){setError(e instanceof Error?e.message:'Unable to save details')}finally{setBusy(false)}}
 async function addPayment(e:React.FormEvent){e.preventDefault();setError('');const a=Number(amount);if(!doc||!Number.isFinite(a)||a<=0)return setError('Enter a positive payment amount.');const row={organization_id:organizationId,document_id:doc,amount:a,method,payment_date:when,reference:reference||null,notes:null};try{if(db){const {error:e}=await db.from('document_payments').insert(row);if(e)throw e;await load()}else localSave('payments',[...payments,{...row,id:crypto.randomUUID()}]);setAmount('');setReference('');setMessage('Payment recorded. No card charge was performed.')}catch(e){setError(e instanceof Error?e.message:'Unable to record payment')}}
 async function del(table:'items'|'payments',id:string){if(!confirm('Delete this record?'))return;try{if(db){const {error:e}=await db.from(table==='items'?'document_items':'document_payments').delete().eq('id',id).eq('organization_id',organizationId);if(e)throw e;await load()}else if(table==='items')localSave('items',items.filter(i=>i.id!==id));else localSave('payments',payments.filter(p=>p.id!==id))}catch(e){setError(e instanceof Error?e.message:'Unable to delete')}}
 return <section className="panel billingV8"><div className="panelHead"><div><h3>Estimate & Invoice Editor</h3><p className="muted">Create detailed line items and save your services for reuse. PDF sending and online payment are not enabled yet.</p></div></div>
 {error&&<div className="error" role="alert">{error}</div>}{message&&<div className="success" role="status">{message}</div>}
 <label className="billingSelect">Choose an estimate or invoice<select value={doc} onChange={e=>{setDoc(e.target.value);setMessage('');setError('')}}><option value="">Select document…</option>{documents.map(d=><option key={d.id} value={d.id}>{d.kind==='invoice'?'INVOICE':'ESTIMATE'} #{d.number} — {clients.find(c=>c.id===d.client_id)?.name||'Customer'}</option>)}</select></label>
 {current&&<><div className="billingTitle"><div><span className="billingEyebrow">{current.kind==='invoice'?'INVOICE':'ESTIMATE'} #{current.number}</span><h3>{current.title}</h3></div><span className="pill">{current.status}</span></div>
 {([{id:'from',label:'From',summary:'Just The Guy Gutters & Exteriors'},{id:'bill',label:current.kind==='invoice'?'Bill To':'Prepared For',summary:customer?.name||'Customer'},{id:'details',label:current.kind==='invoice'?'Invoice Details':'Estimate Details',summary:'Dates, reference, contract'},{id:'items',label:'Items & Pricing',summary:`${currentItems.length} line item(s)`},{id:'payments',label:'Deposits & Payments',summary:`${money(received)} received`}]).map(s=><div className="billingSection" key={s.id}><button type="button" className="billingSectionHeader" onClick={()=>toggle(s.id)} aria-expanded={sections.includes(s.id)}><span className="billingArrow">{sections.includes(s.id)?'▾':'▸'}</span><strong>{s.label}</strong><span className="billingHint">{s.summary}</span></button>{sections.includes(s.id)&&<div className="billingSectionBody">
 {s.id==='from'&&<p><strong>Just The Guy Gutters & Exteriors</strong><br/><span className="muted">Company identity and branding on file</span></p>}
 {s.id==='bill'&&<div className="billingGrid"><p><strong>{customer?.name||'Unknown customer'}</strong><br/>{property?`${property.label} · ${property.address_line1}, ${property.city}, ${property.state} ${property.postal_code}`:'No property attached'}<br/><span className="muted">Document recipient: {current.recipient_email}</span></p><p className="muted">Change customer, property or recipient from the document record. Estimates and invoices can use different contacts.</p></div>}
 {s.id==='details'&&<><div className="billingGrid"><label>{current.kind==='invoice'?'Invoice':'Estimate'} number<input value={current.number} readOnly/></label><label>Issue date<input type="date" value={issued} onChange={e=>setIssued(e.target.value)}/></label><label>{current.kind==='invoice'?'Due date':'Expiration date'}<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><label>Purchase order / reference<input value={po} onChange={e=>setPo(e.target.value)} placeholder="Optional"/></label></div><label>Contract agreement / terms<textarea rows={4} value={terms} onChange={e=>setTerms(e.target.value)} placeholder="Service agreement and customer terms"/></label><button type="button" className="outline" disabled={busy} onClick={()=>void saveDetails()}>Save document details</button><p className="muted">Agreement text is stored internally; signatures and acceptance audit trails are not active.</p></>}
 {s.id==='items'&&<><div className="billingTableWrap"><table className="billingTable"><thead><tr><th>Item</th><th>Price</th><th>Quantity</th><th>Total</th><th></th></tr></thead><tbody>{currentItems.map(i=><tr key={i.id}><td><strong>{i.item_name||i.description}</strong><small>{i.item_name?i.description:''}{i.discount_value?` · Discount: ${i.discount_type==='percent'?i.discount_value+'%':money(Number(i.discount_value))}`:''}{` · Tax: ${i.tax_rate}%`}</small></td><td>{money(Number(i.unit_price))}</td><td>{i.quantity} {i.unit}</td><td><strong>{money(itemTotals(i).total)}</strong></td><td><button type="button" className="iconBtn" title="Edit item" onClick={()=>openItem(i)}>✎</button><button type="button" className="iconBtn" title="Delete item" onClick={()=>void del('items',i.id)}>×</button></td></tr>)}{!currentItems.length&&<tr><td colSpan={5} className="muted">No line items yet. Add a service below.</td></tr>}</tbody></table></div><button type="button" className="outline" onClick={()=>openItem()}>+ Add Item</button><div className="billingTotals"><div><span>Subtotal</span><strong>{money(sums.subtotal)}</strong></div><div><span>Discounts</span><span>−{money(sums.discount)}</span></div><div><span>Tax</span><span>{money(sums.tax)}</span></div><div className="billingGrand"><strong>Total amount</strong><strong>{money(total)}</strong></div></div>{!currentItems.length&&<p className="muted">Until you add line items, the document retains its original entered amount: {money(Number(current.amount))}.</p>}</>}
 {s.id==='payments'&&<><div className="billingTotals"><div><span>Document total</span><strong>{money(total)}</strong></div><div><span>Recorded payments</span><strong>−{money(received)}</strong></div><div className="billingGrand"><strong>Remaining balance</strong><strong>{money(remaining)}</strong></div></div><form className="billingPayment" onSubmit={addPayment}><h4>Record a received payment / deposit</h4><p className="muted">Only record money you've actually received. This does not charge a payment method.</p><div className="billingGrid"><label>Amount ($)<input required type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Method<select value={method} onChange={e=>setMethod(e.target.value)}><option value="cash">Cash</option><option value="check">Check</option><option value="card">Card charged outside HQ</option><option value="other">Other</option></select></label><label>Payment date<input type="date" value={when} onChange={e=>setWhen(e.target.value)}/></label><label>Reference / check number<input value={reference} onChange={e=>setReference(e.target.value)}/></label></div><button className="primary">Record payment</button></form>{currentPayments.map(p=><div className="billingPaymentRow" key={p.id}><span>{money(Number(p.amount))} · {p.method} · {p.payment_date}</span><button className="iconBtn" onClick={()=>void del('payments',p.id)}>×</button></div>)}<p className="muted">Payments from estimates are not automatically credited to invoices yet. Do not record the same deposit twice.</p></>}
 </div>}</div>)}
 <p className="billingFootnote">Document sending, PDF generation, online payment and client e-signatures are not implemented in this version.</p>
 </>}
 {itemOpen&&<div className="billingOverlay" onClick={()=>setItemOpen(false)}><div className="billingItemModal" role="dialog" aria-modal="true" aria-label={editing?'Edit item':'Add item'} onClick={e=>e.stopPropagation()}><div className="billingItemHead"><h3>{editing?'Edit Item':'Add Item'}</h3><button type="button" className="iconBtn" aria-label="Close" onClick={()=>setItemOpen(false)}>×</button></div><form onSubmit={submitItem} className="billingItemForm"><label>Choose a saved item<select defaultValue="" onChange={e=>pickCatalog(e.target.value)}><option value="">New custom item…</option>{catalog.map(c=><option value={c.id} key={c.id}>{c.name} — {money(Number(c.unit_price))}/{c.unit}</option>)}</select></label><label>Name *<input required maxLength={140} value={name} onChange={e=>setName(e.target.value)} placeholder="6-inch gutter"/></label><label>Description<textarea rows={3} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Scope of work, materials and installation notes"/></label><div className="billingGrid"><label>Price (tax excluded) *<input required type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></label><label>Tax %<input type="number" min="0" max="100" step="0.01" value={tax} onChange={e=>setTax(e.target.value)}/></label><label>Quantity *<input required type="number" min="0.001" step="0.001" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label>Unit<input value={unit} onChange={e=>setUnit(e.target.value)} placeholder="each / ft"/></label><label>Discount<input type="number" min="0" step="0.01" value={discount} onChange={e=>setDiscount(e.target.value)}/></label><label>Discount type<select value={discountType} onChange={e=>setDiscountType(e.target.value)}><option value="amount">$ off line item</option><option value="percent">% off line item</option></select></label></div><label className="billingCheck"><input type="checkbox" checked={saveCatalog} onChange={e=>setSaveCatalog(e.target.checked)}/> Save this item to your list for future use</label><div className="billingItemActions"><button type="button" className="outline" onClick={()=>setItemOpen(false)}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':editing?'Save Changes':'Add Item'}</button></div></form></div></div>}
 </section>;
}
