"use client";
import {useCallback,useEffect,useMemo,useState} from 'react';
import {createClient} from '@supabase/supabase-js';
import type {Job} from '../lib/data';

type Employee={id:string;organization_id:string;name:string;hourly_rate:number;active:boolean};
type Entry={id:string;organization_id:string;employee_id:string|null;employee_name:string;work_date:string;hours:number;rate_snapshot:number|null;job_id:string|null;start_time:string|null;end_time:string|null;break_minutes:number|null;notes:string|null};
type PayPeriod={id:string;organization_id:string;employee_id:string;period_start:string;period_end:string;total_hours:number;gross_base_pay:number;paid_at:string|null};
const configured=Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
const api=configured?createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!):null;
const money=(value:number)=>value.toLocaleString('en-US',{style:'currency',currency:'USD'});
const dateKey=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const parseDate=(s:string)=>new Date(`${s}T12:00:00`);
const addDays=(s:string,n:number)=>{const d=parseDate(s);d.setDate(d.getDate()+n);return dateKey(d)};
const monday=(s:string)=>{const d=parseDate(s);d.setDate(d.getDate()-(d.getDay()+6)%7);return dateKey(d)};
const fmtDate=(s:string)=>parseDate(s).toLocaleDateString('en-US',{month:'short',day:'numeric'});
const uuid=()=>crypto.randomUUID();
function stamp(t:string){const a=t.split(':').map(Number);return a[0]*60+a[1]}
function duration(start:string,end:string,breakM:number){let diff=stamp(end)-stamp(start);if(diff<0)diff+=1440;return (diff-breakM)/60}
export default function EmployeeHours({organizationId,jobs,compact=false,onOpen}:{organizationId:string;jobs:Job[];compact?:boolean;onOpen?:()=>void}){
 const [people,setPeople]=useState<Employee[]>([]);const [entries,setEntries]=useState<Entry[]>([]);const [periods,setPeriods]=useState<PayPeriod[]>([]);
 const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const [name,setName]=useState('');const [rate,setRate]=useState('');const [selected,setSelected]=useState('');const [rateEdit,setRateEdit]=useState('');
 const [date,setDate]=useState(()=>dateKey(new Date()));const [start,setStart]=useState('09:00');const [end,setEnd]=useState('17:00');const [breakM,setBreakM]=useState('0');const [job,setJob]=useState('');const [notes,setNotes]=useState('');
 const [week,setWeek]=useState(()=>monday(dateKey(new Date())));const [month,setMonth]=useState(()=>dateKey(new Date()).slice(0,7));const [payDate,setPayDate]=useState(()=>dateKey(new Date()));
 const key=`jtg-hq-v06-${organizationId}`;
 const load=useCallback(async()=>{setLoading(true);setError('');try{if(api){const [a,b,c]=await Promise.all([api.from('employees').select('*').eq('organization_id',organizationId).order('name'),api.from('time_entries').select('*').eq('organization_id',organizationId).order('work_date',{ascending:false}),api.from('pay_periods').select('*').eq('organization_id',organizationId).order('period_start',{ascending:false})]);if(a.error||b.error||c.error)throw new Error(a.error?.message||b.error?.message||c.error?.message);setPeople(a.data||[]);setEntries(b.data||[]);setPeriods(c.data||[])}else{const data=JSON.parse(localStorage.getItem(key)||'{}');setPeople(data.employees||[]);setEntries(data.time_entries||[]);setPeriods(data.pay_periods||[])}}catch(e){setError(e instanceof Error?e.message:'Unable to load employee hours')}finally{setLoading(false)}},[organizationId,key]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{if(!selected&&people.length)setSelected(people[0].id);if(selected&&!people.some(p=>p.id===selected))setSelected(people[0]?.id||'')},[people,selected]);
 useEffect(()=>{setRateEdit(String(people.find(p=>p.id===selected)?.hourly_rate??''))},[selected,people]);
 async function insert(table:'employees'|'time_entries'|'pay_periods',row:Record<string,unknown>){setError('');setNotice('');try{if(api){const {error:e}=await api.from(table).insert({...row,organization_id:organizationId});if(e)throw e;await load()}else{const data=JSON.parse(localStorage.getItem(key)||'{}');data[table]=[{id:uuid(),organization_id:organizationId,...row},...(data[table]||[])];localStorage.setItem(key,JSON.stringify(data));await load()}setNotice('Saved successfully.');return true}catch(e){setError(e instanceof Error?e.message:'Unable to save');return false}}
 async function editEmployee(){const n=Number(rateEdit);if(!Number.isFinite(n)||n<0)return setError('Enter a valid hourly rate.');setError('');try{if(api){const {error:e}=await api.from('employees').update({hourly_rate:n}).eq('id',selected).eq('organization_id',organizationId);if(e)throw e}else{const data=JSON.parse(localStorage.getItem(key)||'{}');data.employees=(data.employees||[]).map((p:Employee)=>p.id===selected?{...p,hourly_rate:n}:p);localStorage.setItem(key,JSON.stringify(data))}await load();setNotice('Rate updated. Earlier entries keep their original rate.')}catch(e){setError(e instanceof Error?e.message:'Unable to update rate')}}
 async function deleteEntry(id:string){if(!window.confirm('Delete this time entry?'))return;setError('');try{if(api){const {error:e}=await api.from('time_entries').delete().eq('id',id).eq('organization_id',organizationId);if(e)throw e}else{const data=JSON.parse(localStorage.getItem(key)||'{}');data.time_entries=(data.time_entries||[]).filter((e:Entry)=>e.id!==id);localStorage.setItem(key,JSON.stringify(data))}await load()}catch(e){setError(e instanceof Error?e.message:'Unable to delete entry')}}
 const person=people.find(p=>p.id===selected);
 const employeeEntries=useMemo(()=>entries.filter(e=>e.employee_id===selected),[entries,selected]);
 const weekEnd=addDays(week,6);
 const weekEntries=employeeEntries.filter(e=>e.work_date>=week&&e.work_date<=weekEnd);
 const weeklyHours=weekEntries.reduce((s,e)=>s+Number(e.hours),0);
 const weeklyPay=weekEntries.reduce((s,e)=>s+Number(e.hours)*Number(e.rate_snapshot??0),0);
 const weekHoursByDay=Array.from({length:7},(_,i)=>{const day=addDays(week,i);return {day,entries:weekEntries.filter(e=>e.work_date===day)}});
 const employeePeriods=periods.filter(p=>p.employee_id===selected);
 const calendarFirst=parseDate(month+'-01');const monthDays=new Date(calendarFirst.getFullYear(),calendarFirst.getMonth()+1,0).getDate();const before=calendarFirst.getDay();
 const monthCells=Array.from({length:Math.ceil((before+monthDays)/7)*7},(_,i)=>{const d=i-before+1;return d<1||d>monthDays?null:`${month}-${String(d).padStart(2,'0')}`});
 function shiftMonth(n:number){const d=parseDate(month+'-01');d.setMonth(d.getMonth()+n);setMonth(dateKey(d).slice(0,7))}
 const label=(id:string|null)=>jobs.find(j=>j.id===id)?.title||'';
 if(compact){const currentWeek=monday(dateKey(new Date()));const currentEnd=addDays(currentWeek,6);return <section className="panel"><div className="panelHead"><h3>Employee hours</h3></div><div className="employeeCompact">{loading?<p>Loading…</p>:people.length?people.map(p=>{const own=entries.filter(e=>e.employee_id===p.id&&e.work_date>=currentWeek&&e.work_date<=currentEnd);const total=own.reduce((s,e)=>s+Number(e.hours),0);return <div key={p.id} className="employeeCompactLine"><strong>{p.name}</strong><span>{total.toFixed(2)} hrs this week</span></div>}):<p>Add employees to track their hours separately.</p>}<button className="outline" onClick={onOpen}>Open employee hours</button>{error&&<p className="error">{error}</p>}</div></section>}
 return <section className="panel employeeTracker"><div className="panelHead"><div><h3>Employees & hours</h3><p className="muted">Separate timesheets, weekly totals and pay records for each person.</p></div></div>
 {error&&<div className="error">{error}</div>}{notice&&<div className="success">{notice}</div>}
 <form className="employeeAdd" onSubmit={async e=>{e.preventDefault();if(!name.trim()||rate===''||Number(rate)<0)return setError('Enter a name and valid rate.');const ok=await insert('employees',{name:name.trim(),hourly_rate:Number(rate),active:true});if(ok){setName('');setRate('')}}}><h4>Add an employee</h4><div className="employeeFields"><label>Name<input required placeholder="e.g. Blue" value={name} onChange={e=>setName(e.target.value)}/></label><label>Hourly rate ($)<input required type="number" min="0" step="0.01" value={rate} onChange={e=>setRate(e.target.value)}/></label><button className="primary">Add employee</button></div></form>
 {!people.length&&!loading?<div className="comingSoon">Add your first employee above to begin recording times.</div>:<><div className="employeeProfiles" role="tablist" aria-label="Employees">{people.map(p=><button type="button" role="tab" aria-selected={selected===p.id} key={p.id} onClick={()=>setSelected(p.id)} className={'employeeProfile '+(selected===p.id?'employeeProfileActive':'')}><strong>{p.name}</strong><small>{money(Number(p.hourly_rate))}/hr</small></button>)}</div>
 {person&&<div className="employeeBody"><div className="employeePersonHeading"><div><h3>{person.name}</h3><p className="muted">Only {person.name}'s entries and calendar are shown below.</p></div><div className="employeeRate"><label>Hourly rate ($)<input type="number" step="0.01" min="0" value={rateEdit} onChange={e=>setRateEdit(e.target.value)}/></label><button type="button" className="outline" onClick={()=>void editEmployee()}>Update rate</button></div></div>
 <form className="employeeTimeForm" onSubmit={async e=>{e.preventDefault();const breakMinutes=Number(breakM);if(!start||!end||start===end||!Number.isInteger(breakMinutes)||breakMinutes<0)return setError('Enter valid start, end, and break times.');const hours=duration(start,end,breakMinutes);if(hours<=0||hours>24)return setError('Shift must be longer than the break and at most 24 hours.');if(employeePeriods.some(p=>p.paid_at&&date>=p.period_start&&date<=p.period_end))return setError('This date belongs to a recorded paid period. Review pay history before changing it.');const ok=await insert('time_entries',{employee_id:person.id,employee_name:person.name,work_date:date,start_time:start,end_time:end,break_minutes:breakMinutes,hours:Math.round(hours*10000)/10000,rate_snapshot:Number(person.hourly_rate),job_id:job||null,notes:notes.trim()||null});if(ok)setNotes('')}}><h4>Add time for {person.name}</h4><div className="employeeFields employeeTimeFields"><label>Date<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label>Start time<input type="time" required value={start} onChange={e=>setStart(e.target.value)}/></label><label>End time<input type="time" required value={end} onChange={e=>setEnd(e.target.value)}/></label><label>Unpaid break (minutes)<input type="number" min="0" step="1" value={breakM} onChange={e=>setBreakM(e.target.value)}/></label><label>Job (optional)<select value={job} onChange={e=>setJob(e.target.value)}><option value="">No job selected</option>{jobs.map(j=><option key={j.id} value={j.id}>{j.title}</option>)}</select></label><label>Notes (optional)<input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Job, travel, etc."/></label></div><p className="muted">Calculated hours: {start&&end&&start!==end&&Number(breakM)>=0?Math.max(0,duration(start,end,Number(breakM))).toFixed(2):'—'} (overnight shifts supported)</p><button className="primary">Save time entry</button></form>
 <div className="employeeWeek"><div className="employeeWeekHead"><div><h4>Weekly timesheet</h4><p className="muted">{fmtDate(week)} – {fmtDate(weekEnd)} · Monday through Sunday</p></div><div className="employeeArrows"><button type="button" className="outline" onClick={()=>setWeek(addDays(week,-7))}>← Previous</button><button type="button" className="outline" onClick={()=>setWeek(monday(dateKey(new Date())))}>This week</button><button type="button" className="outline" onClick={()=>setWeek(addDays(week,7))}>Next →</button></div></div><div className="employeeTotals"><div><span>Weekly hours</span><strong>{weeklyHours.toFixed(2)} hrs</strong></div><div><span>Estimated straight-time pay</span><strong>{money(weeklyPay)}</strong></div></div>{weekHoursByDay.map(({day,entries:dayEntries})=><div className="employeeDayRow" key={day}><div className="employeeDayLabel"><strong>{parseDate(day).toLocaleDateString('en-US',{weekday:'short'})}</strong><small>{fmtDate(day)}</small></div><div className="employeeDailyEntries">{dayEntries.length?dayEntries.map(e=><div key={e.id} className="employeeEntry"><span>{e.start_time&&e.end_time?`${e.start_time}–${e.end_time}`:'Manual entry'} · {Number(e.hours).toFixed(2)} hrs{label(e.job_id)?` · ${label(e.job_id)}`:''}</span><button type="button" aria-label="Delete entry" onClick={()=>void deleteEntry(e.id)}>×</button></div>):<small className="muted">No hours logged</small>}</div><strong>{dayEntries.reduce((s,e)=>s+Number(e.hours),0).toFixed(2)} hrs</strong></div>)}<p className="muted employeeDisclaimer">Estimated pay uses each entry's saved hourly rate. Overtime, taxes, deductions and final payroll are not calculated here.</p></div>
 <div className="employeeCalendar"><div className="employeeWeekHead"><div><h4>{person.name}'s work calendar</h4><p className="muted">Individual daily hours, never a combined employee total.</p></div><div className="employeeArrows"><button type="button" className="outline" onClick={()=>shiftMonth(-1)}>←</button><strong>{calendarFirst.toLocaleDateString('en-US',{month:'long',year:'numeric'})}</strong><button type="button" className="outline" onClick={()=>shiftMonth(1)}>→</button></div></div><div className="employeeMonthGrid">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=><div key={d} className="employeeWeekday">{d}</div>)}{monthCells.map((day,i)=>{const daily=day?employeeEntries.filter(e=>e.work_date===day):[];const hours=daily.reduce((s,e)=>s+Number(e.hours),0);return <button type="button" disabled={!day} key={i} className={'employeeMonthCell '+(!day?'employeeMonthEmpty':'')+(daily.length?' employeeMonthWorked':'')} onClick={()=>day&&setWeek(monday(day))}><span>{day?Number(day.slice(-2)):''}</span>{daily.length>0&&<strong>{hours.toFixed(2)} hrs</strong>}</button>})}</div><p className="muted">Click a date to open its week in the timesheet above.</p></div>
 <div className="employeePayments"><div className="employeeWeekHead"><div><h4>Pay period history</h4><p className="muted">Records are kept per employee even after the week passes.</p></div></div><div className="employeePayActions"><label>Payment date<input type="date" value={payDate} onChange={e=>setPayDate(e.target.value)}/></label><button type="button" className="outline" onClick={async()=>{if(!weekEntries.length)return setError('No hours logged for this week.');if(employeePeriods.some(p=>p.period_start===week&&p.period_end===weekEnd))return setError('This employee already has a saved payment record for this week.');if(!window.confirm(`Record ${person.name}'s pay for ${fmtDate(week)}–${fmtDate(weekEnd)} as paid? Verify overtime, deductions and actual paid amount separately.`))return;await insert('pay_periods',{employee_id:person.id,period_start:week,period_end:weekEnd,total_hours:weeklyHours,gross_base_pay:Math.round(weeklyPay*100)/100,paid_at:payDate})}}>Record selected week as paid</button></div>{employeePeriods.length?<div className="employeeHistory">{employeePeriods.map(p=><div className="employeeHistoryRow" key={p.id}><span><strong>{fmtDate(p.period_start)} – {fmtDate(p.period_end)}</strong><small>{Number(p.total_hours).toFixed(2)} hrs · Paid {p.paid_at||'not marked'}</small></span><b>{money(Number(p.gross_base_pay))}</b></div>)}</div>:<p className="muted">No past pay periods recorded for this employee.</p>}</div>
 </div>}</>}
 </section>;
}
