'use client';
import {useMemo,useState} from 'react';
import {ChevronDown,ChevronRight,Plus,X,Trash2} from 'lucide-react';
import type {Client,Contact,Property,Job} from '../lib/data';

export type DraftItem={id:string;item_name:string;description:string;quantity:number;unit:string;unit_price:number;tax_rate:number;discount_type:'amount'|'percent';discount_value:number};
export type NewDocumentDraft={client_id:string;property_id:string|null;job_id:string|null;kind:'estimate'|'invoice';number:string;title:string;amount:number;status:'draft';recipient_contact_id:string|null;recipient_email:string;issue_date:string;due_date:string|null;purchase_order:string|null;contract_terms:string;notes:string;items:DraftItem[]};
const money=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD'});
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const line=(i:DraftItem)=>{const base=i.quantity*i.unit_price;const discount=Math.min(base,i.discount_type==='percent'?base*i.discount_value/100:i.discount_value);const taxable=base-discount;return {base,discount,tax:taxable*i.tax_rate/100,total:taxable*(1+i.tax_rate/100)};};
const blank=():DraftItem=>({id:crypto.randomUUID(),item_name:'',description:'',quantity:1,unit:'each',unit_price:0,tax_rate:0,discount_type:'amount',discount_value:0});
export default function NewDocumentEditor({kind,clients,contacts,properties,jobs,initialClientId='',initialPropertyId='',onCancel,onSave,saving}:{kind:'estimate'|'invoice';clients:Client[];contacts:Contact[];properties:Property[];jobs:Job[];initialClientId?:string;initialPropertyId?:string;onCancel:()=>void;onSave:(data:NewDocumentDraft)=>Promise<void>;saving:boolean}){
 const [clientId,setClientId]=useState(initialClientId);
 const [propertyId,setPropertyId]=useState(initialPropertyId);
 const [jobId,setJobId]=useState('');
 const [recipientContact,setRecipientContact]=useState('');
 const [email,setEmail]=useState(()=>contacts.find(c=>c.client_id===initialClientId&&c.role===(kind==='estimate'?'estimates':'billing'))?.email||'');
 const [number,setNumber]=useState(()=>`${kind==='estimate'?'EST':'INV'}-${Date.now().toString().slice(-9)}`);
 const [title,setTitle]=useState('');const [issued,setIssued]=useState(today());const [due,setDue]=useState('');const [po,setPo]=useState('');const [terms,setTerms]=useState('');const [notes,setNotes]=useState('');
 const [items,setItems]=useState<DraftItem[]>([]);const [itemOpen,setItemOpen]=useState(false);const [itemDraft,setItemDraft]=useState<DraftItem>(blank());const [editingId,setEditingId]=useState<string|null>(null);
 const [sections,setSections]=useState(['customer','details','items','terms']);const [error,setError]=useState('');
 const totals=useMemo(()=>items.reduce((s,i)=>{const n=line(i);return {subtotal:s.subtotal+n.base,discount:s.discount+n.discount,tax:s.tax+n.tax,total:s.total+n.total}},{subtotal:0,discount:0,tax:0,total:0}),[items]);
 const contactList=contacts.filter(c=>c.client_id===clientId);
 function changeClient(id:string){setClientId(id);setPropertyId('');setJobId('');const c=contacts.find(c=>c.client_id===id&&c.role===(kind==='estimate'?'estimates':'billing')&&c.email);setRecipientContact(c?.id||'');setEmail(c?.email||'');}
 function editItem(i?:DraftItem){setItemDraft(i?{...i}:blank());setEditingId(i?.id||null);setError('');setItemOpen(true);}
 function addItem(e:React.FormEvent){e.preventDefault();const i=itemDraft;const x=[i.quantity,i.unit_price,i.tax_rate,i.discount_value];if(!i.item_name.trim()||x.some(n=>!Number.isFinite(n))||i.quantity<=0||i.unit_price<0||i.tax_rate<0||i.tax_rate>100||i.discount_value<0||(i.discount_type==='percent'&&i.discount_value>100)||(i.discount_type==='amount'&&i.discount_value>i.quantity*i.unit_price)){setError('Check item name, quantity, price, tax, and discount.');return;}setItems(p=>editingId?p.map(v=>v.id===editingId?i:v):[...p,i]);setItemOpen(false);setError('');}
 const updateItem=(key:keyof DraftItem,value:string)=>setItemDraft(p=>({...p,[key]:['quantity','unit_price','tax_rate','discount_value'].includes(key)?Number(value):value}));
 async function save(e:React.FormEvent){e.preventDefault();setError('');if(!clientId)return setError('Choose a customer.');if(!number.trim())return setError('Enter a document number.');if(!items.length)return setError('Add at least one line item before saving.');if(!email.trim()||!/^\S+@\S+\.\S+$/.test(email.trim()))return setError('Enter a valid recipient email.');try{await onSave({client_id:clientId,property_id:propertyId||null,job_id:jobId||null,kind,number:number.trim(),title:title.trim()||items[0].item_name,amount:Math.round(totals.total*100)/100,status:'draft',recipient_contact_id:recipientContact||null,recipient_email:email.trim(),issue_date:issued,due_date:due||null,purchase_order:po.trim()||null,contract_terms:terms,notes,items});}catch(e){setError(e instanceof Error?e.message:'Unable to save draft');}}
 const label=kind==='estimate'?'Estimate':'Invoice';
 const section=(id:string,name:string,sub:string,children:React.ReactNode)=><div className="billingSection" key={id}><button className="billingSectionHeader" type="button" onClick={()=>setSections(p=>p.includes(id)?p.filter(s=>s!==id):[...p,id])}><span className="billingArrow">{sections.includes(id)?<ChevronDown size={16}/>:<ChevronRight size={16}/>}</span><strong>{name}</strong><span className="billingHint">{sub}</span></button>{sections.includes(id)&&<div className="billingSectionBody">{children}</div>}</div>;
 return <section className="panel billingV8"><div className="panelHead"><div><h3>New {label}</h3><p className="muted">Fill out your {kind}, add services, and save it all as one draft. No preliminary document form.</p></div><button className="outline" type="button" onClick={onCancel}><X size={16}/> Cancel</button></div>
 <form onSubmit={save} className="newDocForm">
 {section('from','From','Just The Guy Gutters & Exteriors',<strong>Just The Guy Gutters & Exteriors</strong>)}
 {section('customer',kind==='estimate'?'Prepared For':'Bill To','Customer, property & email recipient',<div className="billingGrid"><label>Customer *<select required value={clientId} onChange={e=>changeClient(e.target.value)}><option value="">Select customer…</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Property<select value={propertyId} onChange={e=>{setPropertyId(e.target.value);setJobId('')}}><option value="">No property selected</option>{properties.filter(p=>p.client_id===clientId).map(p=><option key={p.id} value={p.id}>{p.label} — {p.address_line1}</option>)}</select></label><label>Related job (optional)<select value={jobId} onChange={e=>setJobId(e.target.value)}><option value="">No job selected</option>{jobs.filter(j=>j.client_id===clientId&&(!propertyId||j.property_id===propertyId)).map(j=><option key={j.id} value={j.id}>{j.title}</option>)}</select></label><label>Recipient contact<select value={recipientContact} onChange={e=>{const c=contactList.find(c=>c.id===e.target.value);setRecipientContact(e.target.value);if(c?.email)setEmail(c.email)}}><option value="">Enter email manually</option>{contactList.map(c=><option key={c.id} value={c.id}>{c.name} ({c.role}){c.email?' — '+c.email:''}</option>)}</select></label><label className="newDocFull">{label} recipient email *<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="accounting@example.com"/></label></div>)}
 {section('details',label+' Details','Number, issue date and reference',<div className="billingGrid"><label>{label} Number *<input required value={number} onChange={e=>setNumber(e.target.value)}/></label><label>Optional title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Defaults to first line item"/></label><label>Issue date<input type="date" required value={issued} onChange={e=>setIssued(e.target.value)}/></label><label>{kind==='estimate'?'Expiration date':'Due date'}<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><label>Purchase order / reference<input value={po} onChange={e=>setPo(e.target.value)}/></label></div>)}
 {section('items','Items & Pricing',`${items.length} item(s) · ${money(totals.total)}`,<><div className="billingTableWrap"><table className="billingTable"><thead><tr><th>Item</th><th>Price</th><th>Quantity</th><th>Total</th><th></th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td><strong>{i.item_name}</strong><small>{i.description}{i.discount_value?` · ${i.discount_type==='percent'?i.discount_value+'%':money(i.discount_value)} discount`:''} · Tax {i.tax_rate}%</small></td><td>{money(i.unit_price)}</td><td>{i.quantity} {i.unit}</td><td>{money(line(i).total)}</td><td><button type="button" className="iconBtn" onClick={()=>editItem(i)}>✎</button><button type="button" className="iconBtn" onClick={()=>setItems(p=>p.filter(v=>v.id!==i.id))}><Trash2 size={16}/></button></td></tr>)}{!items.length&&<tr><td className="muted" colSpan={5}>Add a line item to start building the {kind}.</td></tr>}</tbody></table></div><button type="button" className="outline" onClick={()=>editItem()}><Plus size={17}/> Add Item</button><div className="billingTotals"><div><span>Subtotal</span><strong>{money(totals.subtotal)}</strong></div><div><span>Discounts</span><strong>−{money(totals.discount)}</strong></div><div><span>Tax</span><strong>{money(totals.tax)}</strong></div><div className="billingGrand"><strong>Total amount</strong><strong>{money(totals.total)}</strong></div></div></>)}
 {section('terms',kind==='estimate'?'Contract & Deposit':'Payment Terms','Agreement and internal notes',<><label>Contract agreement / terms<textarea rows={4} value={terms} onChange={e=>setTerms(e.target.value)} placeholder="Contract terms, scope, warranties and payment conditions"/></label><label>Internal notes<textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></label><p className="muted">Online deposits, signatures, PDF generation and email delivery are not active yet. This saves an internal draft only.</p></>)}
 {error&&<div className="error" role="alert">{error}</div>}
 <div className="newDocActions"><button type="button" className="outline" onClick={onCancel}>Cancel</button><button type="submit" className="primary" disabled={saving}>{saving?'Saving…':'Save Draft'}</button></div>
 </form>
 {itemOpen&&<div className="billingOverlay" onClick={()=>setItemOpen(false)}><div className="billingItemModal" role="dialog" aria-modal="true" aria-label={editingId?'Edit Item':'Add Item'} onClick={e=>e.stopPropagation()}><div className="billingItemHead"><h3>{editingId?'Edit Item':'Add Item'}</h3><button type="button" className="iconBtn" onClick={()=>setItemOpen(false)}><X size={20}/></button></div><form className="billingItemForm" onSubmit={addItem}><label>Name *<input autoFocus required value={itemDraft.item_name} onChange={e=>updateItem('item_name',e.target.value)} placeholder="6-inch seamless gutters"/></label><label>Description<textarea value={itemDraft.description} onChange={e=>updateItem('description',e.target.value)} rows={3}/></label><div className="billingGrid"><label>Price (tax excluded)<input type="number" min="0" step="0.01" value={itemDraft.unit_price} onChange={e=>updateItem('unit_price',e.target.value)}/></label><label>Tax %<input type="number" min="0" max="100" step="0.01" value={itemDraft.tax_rate} onChange={e=>updateItem('tax_rate',e.target.value)}/></label><label>Quantity<input type="number" min="0.001" step="0.001" value={itemDraft.quantity} onChange={e=>updateItem('quantity',e.target.value)}/></label><label>Unit<input value={itemDraft.unit} onChange={e=>updateItem('unit',e.target.value)}/></label><label>Discount<input type="number" min="0" step="0.01" value={itemDraft.discount_value} onChange={e=>updateItem('discount_value',e.target.value)}/></label><label>Discount type<select value={itemDraft.discount_type} onChange={e=>updateItem('discount_type',e.target.value)}><option value="amount">$ amount</option><option value="percent">Percentage</option></select></label></div>{error&&<div className="error">{error}</div>}<div className="billingItemActions"><button type="button" className="outline" onClick={()=>setItemOpen(false)}>Cancel</button><button className="primary">{editingId?'Save Item':'Add Item'}</button></div></form></div></div>}
 </section>;
}
